{% set name = "eikon" %}
{% set version = "1.1.17" %}
{% set sha256 = "2aff9214739cf1443766590b2db5211557ffe8eca388df694d935fbe75d32d51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil
    - deprecation
    - appdirs >=1.4.3
    - httpx >=0.18.0
    - nest-asyncio >=1.5.1
    - websocket-client >=0.54.0,!=1.0.0
    - pandas
    - numpy >=1.11.0
    - python-dateutil
    - deprecation
    - certifi
    - h2 ==3.*
    - idna ==2.*
    - rfc3986 ==1.*
    - requests ==2.*
    - chardet
    - urllib3
    - packaging

test:
  imports:
    - eikon

about:
  home: https://developers.refinitiv.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Python API for accessing Eikon data directly from any application running on your desktop
  description: |
    The Eikon Data API provide simple access to users who require programmatic access to Eikon data on the desktop. 
    This API is intended for Eikon users. Applications and scripts using this API must be run beside Eikon on the same desktop machine for the Eikon user only.
  doc_url: https://developers.refinitiv.com/eikon-apis/eikon-data-api/docs
  dev_url: https://developers.refinitiv.com/eikon-apis/eikon-data-api/

extra:
  recipe-maintainers:
    - wiphoo
    - Mhoian
    - PFaurel
